use constraints;

/*  
THIS IS FISRST WAY
CREATE TABLE STUDENT(
	NAME varchar(50) NOT NULL,
    ROLL CHAR(4) PRIMARY KEY,
    EMAIL VARCHAR(30) UNIQUE,
    ADDRESS VARCHAR(200),
    AGE INT CHECK(AGE>10)
);

THIS IS SECOND WAY


CREATE TABLE STUDENT(
	NAME varchar(50) NOT NULL,
    ROLL CHAR(4),
    EMAIL VARCHAR(30),
    ADDRESS VARCHAR(200),
    AGE INT,
    CONSTRAINT CHECK(AGE>10),
    CONSTRAINT UNIQUE(EMAIL),
    CONSTRAINT PRIMARY KEY(ROLL)
);

/*
CREATE TABLE STUDENT(
	NAME varchar(50) NOT NULL,
    ROLL CHAR(4) PRIMARY KEY,
    EMAIL VARCHAR(30) UNIQUE,
    ADDRESS VARCHAR(200),
    AGE INT CHECK(AGE>10)
);
*

CREATE TABLE LIBRARY(
	BOOK_NAME VARCHAR(60),
    HIRED_STUDENT_ROLL CHAR(4),
    CONSTRAINT FOREIGN KEY(HIRED_STUDENT_ROLL) REFERENCES STUDENT(ROLL)
);
 /
 
 -- INSERT INTO STUDENT (NAME,ROLL,AGE, EMAIL) VALUES("MANIK", 6352,12,'HEY');
 
 
-- COMPOSIT KEY 
CREATE TABLE COURSES
(
	UNIVERSITY VARCHAR(20),
    COURSE_NAME VARCHAR(20),
    CREDIT INT,
    CONSTRAINT DOUBLE_PRIMARY_KEY PRIMARY KEY(COURSE_NAME, UNIVERSITY)
);
*/
-- SELECT *
-- FROM STUDENT

-- SELECT ROLL, NAME, EMAIL, AGE
-- FROM STUDENT

-- SELECT *
-- FROM STUDENT
-- WHERE NAME= 'MORSALIN ISLAM'

-- SELECT ADDRESS
-- FROM STUDENT
-- WHERE ADDRESS = 'RONGPUR'

-- COMPARISION OPERATOR

SELECT AGE<20, AGE>20,AGE+5
FROM STUDENT


